export const FETCH_USERS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_USERS_LOADING = 'FETCH_USERS_LOADING';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';

export const EDIT_USER = 'EDIT_USER';

